#!/usr/bin/env bash
# Takes 'domain' and 'subdomain' parameters and displays information for the specified subdomain

display_info () {
    # Check if dig is available
    if ! command -v dig &> /dev/null; then
        echo "Error: 'dig' command not found. Please install it."
        exit 1
    fi

    script=$(dig "$2.$1" | grep -A1 'ANSWER SECTION:' | tr '\t' '\n' | tail -2 | tr '\n' ' ')
    echo "$2 $script" | awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3}'
}

if [ "$#" -eq 2 ]; then
    display_info "$1" "$2"
else
    subdomains=("www" "lb-01" "web-01" "web-02")
    for subdomain in "${subdomains[@]}"; do
        display_info "$1" "$subdomain"
    done
fi
