#!/usr/bin/env bash
# Configuring HAProxy load balancer
 
sudo apt-get -y update
sudo apt-get -y install software-properties-common
sudo add-apt repository -y ppa:vbernat/haproxy-2.0
sudo app-get -y update
sudo apt-get -y install haproxy

balancer="\
frontend haproxy_balancer
    bind *:80
    mode http
    default_backend webservers

backend webservers
    balance roundrobin
    server 295888-web-01 34.207.58.155:80 check
    server 295888-web-02 54.160.85.28:80 check
"

sudo cp -a /etc/haproxy/haproxy.cfg{,.orig}
echo "$balancer" | sudo tee -a /etc/haproxy/haproxy.cfg > /dev/null
sudo service haproxy start
